# Generated by Django 3.2.7 on 2021-09-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
