# Generated by Django 3.2.7 on 2021-09-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='about',
            field=models.TextField(default='about me...', max_length=255),
        ),
    ]
