# Generated by Django 3.2.7 on 2021-09-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_newuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='following',
            field=models.JSONField(default=dict, verbose_name='Following'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='photo',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Boy'), (3, 'Girl')], default=1),
        ),
    ]
