# Generated by Django 3.2.7 on 2021-09-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210928_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='following',
        ),
    ]
