# Generated by Django 3.2.7 on 2021-09-28 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_newuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
