# Generated by Django 3.2.7 on 2021-09-30 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_newuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
